<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->

<svg
   width="112.52426mm"
   height="156.60059mm"
   viewBox="0 0 112.52426 156.60059"
   version="1.1"
   id="svg1"
   inkscape:export-filename="file.svg"
   inkscape:export-xdpi="96"
   inkscape:export-ydpi="96"
   sodipodi:docname="makefile.svg"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <sodipodi:namedview
     id="namedview1"
     pagecolor="#ffffff"
     bordercolor="#000000"
     borderopacity="0.25"
     inkscape:showpageshadow="2"
     inkscape:pageopacity="0.0"
     inkscape:pagecheckerboard="0"
     inkscape:deskcolor="#d1d1d1"
     inkscape:document-units="px"
     showguides="true">
    <inkscape:page
       x="0"
       y="0"
       width="112.52426"
       height="156.60059"
       id="page2"
       margin="0"
       bleed="0" />
  </sodipodi:namedview>
  <defs
     id="defs1">
    <inkscape:path-effect
       effect="fillet_chamfer"
       id="path-effect6"
       is_visible="true"
       lpeversion="1"
       nodesatellites_param="F,0,0,1,0,0,0,1 @ F,0,0,1,0,0,0,1 @ F,0,0,1,0,1.9156323,0,1 @ F,0,0,1,0,1.9156323,0,1"
       radius="1.9156323"
       unit="mm"
       method="auto"
       mode="F"
       chamfer_steps="1"
       flexible="false"
       use_knot_distance="true"
       apply_no_radius="true"
       apply_with_radius="true"
       only_selected="false"
       hide_knots="false" />
    <inkscape:path-effect
       effect="fillet_chamfer"
       id="path-effect4"
       is_visible="true"
       lpeversion="1"
       nodesatellites_param="F,0,0,1,0,13.832829,0,1 @ F,0,0,1,0,2.3875044,0,1 @ F,0,0,1,0,18.347366,0,1 @ F,0,0,1,0,0.52069697,0,1"
       radius="1.4564632"
       unit="mm"
       method="auto"
       mode="F"
       chamfer_steps="1"
       flexible="false"
       use_knot_distance="true"
       apply_no_radius="true"
       apply_with_radius="true"
       only_selected="false"
       hide_knots="false" />
    <inkscape:path-effect
       effect="fillet_chamfer"
       id="path-effect3"
       is_visible="true"
       lpeversion="1"
       nodesatellites_param="F,0,0,1,0,0,0,1 @ F,0,0,1,0,0,0,1 @ F,0,0,1,0,1.9156323,0,1 @ F,0,0,1,0,1.9156323,0,1"
       radius="1.9156323"
       unit="mm"
       method="auto"
       mode="F"
       chamfer_steps="1"
       flexible="false"
       use_knot_distance="true"
       apply_no_radius="true"
       apply_with_radius="true"
       only_selected="false"
       hide_knots="false" />
    <linearGradient
       id="swatch1"
       inkscape:swatch="solid">
      <stop
         style="stop-color:#000000;stop-opacity:1;"
         offset="0"
         id="stop1" />
    </linearGradient>
    <inkscape:path-effect
       effect="fillet_chamfer"
       id="path-effect1"
       is_visible="true"
       lpeversion="1"
       nodesatellites_param="F,0,0,1,0,11.458333,0,1 @ F,0,0,1,0,31.808333,0,1 @ F,0,0,1,0,11.458333,0,1 @ F,0,0,1,0,11.458333,0,1"
       radius="11.458334"
       unit="mm"
       method="auto"
       mode="F"
       chamfer_steps="1"
       flexible="false"
       use_knot_distance="true"
       apply_no_radius="true"
       apply_with_radius="true"
       only_selected="false"
       hide_knots="false" />
  </defs>
  <path
     style="fill:#e7e7e7;fill-opacity:1;stroke:none;stroke-width:0.777;stroke-dasharray:none;stroke-opacity:1"
     id="rect1"
     width="112.52426"
     height="156.60059"
     x="44.076321"
     y="116.67262"
     ry="0"
     inkscape:path-effect="#path-effect1"
     sodipodi:type="rect"
     rx="0"
     d="m 55.534654,116.67262 h 69.257596 a 31.808333,31.808333 45 0 1 31.80833,31.80834 v 113.33392 a 11.458333,11.458333 135 0 1 -11.45833,11.45833 H 55.534654 A 11.458333,11.458333 45 0 1 44.076321,261.81488 V 128.13096 a 11.458333,11.458333 135 0 1 11.458333,-11.45834 z"
     transform="translate(-44.076322,-116.67262)" />
  <g
     inkscape:label="Camada 1"
     inkscape:groupmode="layer"
     id="layer1"
     transform="translate(-44.076321,-116.67262)">
    <g
       id="g4"
       transform="translate(-3.5934242,-3.6509369)">
      <path
         style="fill:#e46800;stroke-width:0.977;fill-opacity:1"
         id="rect2"
         width="18.915302"
         height="74.08493"
         x="177.54654"
         y="94.150398"
         ry="0"
         transform="rotate(31.731687,-2.9446998,3.309363)"
         inkscape:path-effect="#path-effect3"
         sodipodi:type="rect"
         rx="0"
         d="m 177.54654,94.150398 h 18.9153 V 166.3197 a 1.9156323,1.9156323 135 0 1 -1.91563,1.91563 h -15.08404 a 1.9156323,1.9156323 45 0 1 -1.91563,-1.91563 z" />
      <path
         style="fill:#a64c00;fill-opacity:1;stroke-width:0.977"
         id="path4"
         width="18.915302"
         height="74.08493"
         x="177.54654"
         y="94.150398"
         ry="0"
         transform="matrix(0.84765409,0.53054439,-0.11227704,0.17518094,-33.611227,59.323887)"
         inkscape:path-effect="#path-effect6"
         sodipodi:type="rect"
         rx="0"
         d="m 177.54654,94.150398 h 18.9153 V 166.3197 a 1.9156323,1.9156323 135 0 1 -1.91563,1.91563 h -15.08404 a 1.9156323,1.9156323 45 0 1 -1.91563,-1.91563 z" />
      <path
         style="fill:#0a0a08;stroke-width:0.850835"
         id="rect3"
         width="18.868063"
         height="56.327076"
         x="-96.000252"
         y="163.80736"
         ry="0"
         transform="matrix(0.50102321,-0.86543622,1.0170811,0.60067024,-34.881061,-16.622078)"
         inkscape:path-effect="#path-effect4"
         sodipodi:type="rect"
         rx="0"
         d="m -82.167423,163.80736 h 2.64773 a 2.3875044,2.3875044 45 0 1 2.387504,2.3875 v 35.59221 a 18.347366,18.347366 135 0 1 -18.347366,18.34736 h 0 a 0.52069697,0.52069697 45 0 1 -0.520697,-0.52069 v -41.97355 a 13.832829,13.832829 135 0 1 13.832829,-13.83283 z" />
    </g>
  </g>
</svg>
